<section class="output-show-summary-grid">
    <article class="panel entry-document-card output-document-panel">
        <div class="panel-heading"><p class="eyebrow">Documento</p><h2>Información de la salida</h2></div>
        <dl class="detail-list detail-list--entry">
            <div><dt>Fecha de salida</dt><dd>{{ $nota->fecha_salida?->format('d/m/Y') }}</dd></div><div><dt>Motivo</dt><dd>{{ $nota->motivoVisible() }}</dd></div><div><dt>Documento origen</dt><dd>{{ $origen }}</dd></div>
            @if ($nota->ordenOperacion)<div><dt>Tipo de orden</dt><dd>{{ $nota->ordenOperacion?->tipoOrden?->codigo ?? '—' }}</dd></div><div><dt>Área del trabajo</dt><dd>{{ $nota->area_trabajo ?: 'GENERAL / histórica' }}</dd></div><div><dt>Cliente</dt><dd>{{ $nota->ordenOperacion?->cliente?->razon_social ?? '—' }}</dd></div>@if ($nota->ordenOperacion?->vehiculo)<div><dt>Vehículo</dt><dd>{{ $nota->ordenOperacion->vehiculo->placa ?: ($nota->ordenOperacion->vehiculo->codigo_interno ?: '—') }}</dd></div>@endif
            @elseif ($nota->proforma)<div><dt>Cliente</dt><dd>{{ $nota->proforma?->cliente?->razon_social ?? '—' }}</dd></div>@endif
            <div><dt>Recibido por</dt><dd>{{ $nota->recibido_por_nombre ?: ($nota->entregado_a ?: 'No registrado') }}@if ($nota->recibido_por_dni) · DNI {{ $nota->recibido_por_dni }} @endif</dd></div>
            <div><dt>Entregado por</dt><dd>{{ $nota->entregado_por_nombre ?: ($nota->confirmador?->empleado?->nombre_completo ?? ($nota->confirmador?->username ?? '—')) }}@if ($nota->entregado_por_dni) · DNI {{ $nota->entregado_por_dni }} @endif</dd></div>
            <div><dt>Confirmado</dt><dd>{{ $nota->confirmado_en?->format('d/m/Y H:i') ?? '—' }}</dd></div>
        </dl>
    </article>
    <article class="panel entry-total-card output-total-card"><span class="entry-total-card__icon output-total-card__icon"><x-ui.icon name="exit" :size="28" /></span><span>Productos distintos</span><strong>{{ $productosDistintos }}</strong>@if ($puedeTotalizarCantidad)<small>Cantidad entregada: <x-ui.quantity :value="$nota->detalles->sum('cantidad')" /> {{ $unidadResumen }}</small>@else<small>Ver cantidades en el detalle</small>@endif<div class="entry-total-card__amount"><span>Valor de salida</span><strong>S/ {{ number_format((float) $nota->detalles->sum('subtotal'), 2, '.', ',') }}</strong></div></article>
</section>

@if ($nota->observacion)<div class="notice notice--info notice--block"><x-ui.icon name="info" :size="18" /><span>{{ $nota->observacion }}</span></div>@endif

<section class="panel entry-detail-card">
    <div class="panel-heading panel-heading--split"><div><p class="eyebrow">Verdad física</p><h2>Productos entregados</h2><p>Estas cantidades son las que descontaron físicamente el inventario.</p></div><div class="panel-heading__actions"><a href="{{ route('inventario.index') }}" class="button button--ghost button--small"><x-ui.icon name="inventory" :size="16" /> Ver inventario</a><a href="{{ route('movimientos.index', ['q' => $nota->id]) }}" class="button button--ghost button--small"><x-ui.icon name="movements" :size="16" /> Ver movimientos</a></div></div>
    <div class="table-wrap table-wrap--responsive"><table class="data-table data-table--responsive output-detail-table output-detail-table--compact"><thead><tr><th>Producto</th><th>Cantidad / tratamiento</th><th>Ubicación</th><th>Valorización</th><th>Plan y observación</th></tr></thead><tbody>
        @foreach ($nota->detalles as $detalle)<tr><td data-label="Producto"><a href="{{ route('productos.show', $detalle->producto_id) }}" class="table-primary-link">{{ $detalle->producto?->codigo }}</a><span>{{ $detalle->producto?->descripcion }}</span></td><td data-label="Cantidad / tratamiento"><strong><x-ui.quantity :value="$detalle->cantidad" /> {{ $detalle->producto?->unidadMedida?->codigo }}</strong><span>{{ $detalle->tratamientoVisible() }}</span></td><td data-label="Ubicación"><span class="location-chip"><x-ui.icon name="shelf" :size="14" /> {{ $detalle->repisa?->codigo }}</span></td><td data-label="Valorización"><span>S/ {{ number_format((float) $detalle->costo_unitario_promedio, 2, '.', ',') }} c/u</span><strong>S/ {{ number_format((float) $detalle->subtotal, 2, '.', ',') }}</strong></td><td data-label="Plan y observación">@if ($detalle->tratamiento === 'CONSUMO' && $detalle->cantidad_planificada_aplicada !== null)<span>Plan: <x-ui.quantity :value="$detalle->cantidad_planificada_aplicada" /></span>@if ((float) $detalle->cantidad_excedente > 0)<strong>Exceso: <x-ui.quantity :value="$detalle->cantidad_excedente" /></strong><small>{{ $detalle->motivoExcedenteVisible() }}</small>@endif @else<span>Sin aplicación al plan</span>@endif<small>{{ $detalle->observacion ?: 'Sin observación' }}</small></td></tr>@endforeach
    </tbody></table></div>
</section>
