<?php

use App\Support\PermisoSistema as P;

return [
    'roles' => [
        'ADMINISTRADOR' => [
            'nombre' => 'Administrador',
            'perfil' => 'Dueño y supervisión general',
            'descripcion' => 'Acceso integral, indicadores, auditoría, Kardex valorizado y administración del sistema.',
            'permisos' => ['*'],
            'modulos' => [
                'Comercial y logística',
                'Compras y proveedores',
                'Almacén',
                'Control de planta',
                'Contabilidad',
                'Usuarios y seguridad',
                'Kardex valorizado',
                'Auditoría e indicadores',
            ],
        ],

        'COMERCIAL_LOGISTICA' => [
            'nombre' => 'Comercial y logística',
            'perfil' => 'Clientes, ventas y compras',
            'descripcion' => 'Gestiona clientes, proveedores, cotizaciones, compras y órdenes comerciales OM, OS y OP.',
            'permisos' => [
                P::DASHBOARD_VER,
                P::PRODUCTOS_VER,
                P::INVENTARIO_VER,
                P::ORDENES_VER,
                P::ORDENES_CREAR_COMERCIAL,
                P::ORDENES_EDITAR_COMERCIAL,
                P::ORDENES_ANULAR_COMERCIAL,
                P::ORDENES_VER_COSTOS,
                P::ORDENES_GESTIONAR_COSTOS,
                P::CLIENTES_GESTIONAR,
                P::PROVEEDORES_GESTIONAR,
                P::REQUERIMIENTOS_COMPRA_GESTIONAR,
                P::COMPRAS_GESTIONAR,
                P::PROFORMAS_VER,
                P::PROFORMAS_COTIZAR,
            ],
            'modulos' => [
                'Clientes y proveedores',
                'Cotizaciones y compras',
                'Cotizaciones directas y proformas recibidas',
                'Órdenes OM, OS y OP',
            ],
        ],

        'ALMACEN' => [
            'nombre' => 'Almacén',
            'perfil' => 'Inventario y despacho',
            'descripcion' => 'Controla productos, ubicaciones, ingresos, salidas, alertas y proformas de venta directa.',
            'permisos' => [
                P::DASHBOARD_VER,
                P::PRODUCTOS_VER,
                P::PRODUCTOS_GESTIONAR,
                P::INVENTARIO_VER,
                P::INVENTARIO_CONFIGURAR,
                P::REPISAS_VER,
                P::REPISAS_GESTIONAR,
                P::MOVIMIENTOS_VER,
                P::INGRESOS_VER,
                P::INGRESOS_REGISTRAR,
                P::SALIDAS_LISTAR,
                P::SALIDAS_VER,
                P::SALIDAS_REGISTRAR,
                P::SALIDAS_ANULAR,
                P::ALERTAS_VER,
                P::ALERTAS_GESTIONAR,
                P::REQUERIMIENTOS_COMPRA_CREAR,
                P::ORDENES_VER,
                P::PROFORMAS_VER,
                P::PROFORMAS_CREAR,
            ],
            'modulos' => [
                'Productos e inventario',
                'Ingresos y salidas',
                'Alertas y movimientos',
                'Proformas de venta directa',
            ],
        ],

        'JEFE_PLANTA' => [
            'nombre' => 'Jefe de planta',
            'perfil' => 'Ejecución de producción',
            'descripcion' => 'Consulta órdenes y materiales entregados; inicia, actualiza y cierra la ejecución productiva.',
            'permisos' => [
                P::DASHBOARD_VER,
                P::ORDENES_VER,
                P::ORDENES_GESTIONAR_ESTADO,
                P::SALIDAS_VER,
                P::PRODUCCION_VER,
                P::PRODUCCION_GESTIONAR,
            ],
            'modulos' => [
                'Órdenes asignadas',
                'Materiales entregados',
                'Avance de producción',
                'Cierre operativo',
            ],
        ],

        'CONTABILIDAD' => [
            'nombre' => 'Contabilidad',
            'perfil' => 'Cobros, pagos y conciliación',
            'descripcion' => 'Visualiza únicamente documentos comerciales finalizados para registrar cobros, pagos y conciliaciones.',
            'permisos' => [
                P::DASHBOARD_VER,
                P::CONTABILIDAD_VER,
            ],
            'modulos' => [
                'Cuentas por cobrar',
                'Cuentas por pagar',
                'Facturas externas',
                'Conciliación',
            ],
        ],
    ],

    'catalogo' => [
        P::DASHBOARD_VER => 'Dashboard del perfil',
        P::PRODUCTOS_VER => 'Consultar productos',
        P::PRODUCTOS_GESTIONAR => 'Crear y modificar productos',
        P::INVENTARIO_VER => 'Consultar inventario',
        P::INVENTARIO_CONFIGURAR => 'Configurar inventario y realizar conteos físicos',
        P::REPISAS_VER => 'Consultar repisas',
        P::REPISAS_GESTIONAR => 'Gestionar repisas',
        P::MOVIMIENTOS_VER => 'Consultar movimientos',
        P::INGRESOS_VER => 'Consultar ingresos',
        P::INGRESOS_REGISTRAR => 'Registrar ingresos',
        P::SALIDAS_LISTAR => 'Listar notas de salida',
        P::SALIDAS_VER => 'Consultar una nota de salida',
        P::SALIDAS_REGISTRAR => 'Registrar salidas',
        P::SALIDAS_ANULAR => 'Anular salidas',
        P::ALERTAS_VER => 'Consultar alertas',
        P::ALERTAS_GESTIONAR => 'Evaluar y atender alertas',
        P::ORDENES_VER => 'Consultar órdenes',
        P::ORDENES_CREAR_COMERCIAL => 'Crear OP, OM y OS',
        P::ORDENES_EDITAR_COMERCIAL => 'Editar OP, OM y OS',
        P::ORDENES_ANULAR_COMERCIAL => 'Anular OP, OM y OS',
        P::ORDENES_GESTIONAR_ESTADO => 'Activar y cerrar ejecución',
        P::ORDENES_VER_COSTOS => 'Consultar costos reales de las órdenes',
        P::ORDENES_GESTIONAR_COSTOS => 'Registrar y anular costos directos de las órdenes',
        P::CLIENTES_GESTIONAR => 'Gestionar clientes',
        P::PROVEEDORES_GESTIONAR => 'Gestionar proveedores',
        P::REQUERIMIENTOS_COMPRA_CREAR => 'Crear y enviar requerimientos de compra desde Almacén',
        P::REQUERIMIENTOS_COMPRA_GESTIONAR => 'Recibir y gestionar requerimientos de compra',
        P::COMPRAS_GESTIONAR => 'Gestionar compras',
        P::PROFORMAS_VER => 'Consultar proformas y cotizaciones al cliente',
        P::PROFORMAS_CREAR => 'Crear y enviar proformas de venta directa desde Almacén',
        P::PROFORMAS_COTIZAR => 'Cotizar, cerrar, versionar y anular proformas/cotizaciones',
        P::PROFORMAS_GESTIONAR => 'Permiso heredado de proformas',
        P::PRODUCCION_VER => 'Consultar producción',
        P::PRODUCCION_GESTIONAR => 'Gestionar avance productivo',
        P::CONTABILIDAD_VER => 'Consultar puente contable',
        P::KARDEX_VER => 'Consultar Kardex valorizado',
        P::AUDITORIA_VER => 'Consultar auditoría',
        P::USUARIOS_GESTIONAR => 'Gestionar usuarios y roles',
    ],
];
